<?php

/**
 * @file
 * Module file for the OCHA AI Chat module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function ocha_ai_chat_theme(): array {
  return [
    'ocha_ai_chat_chat_popup' => [
      'variables' => [
        // The headling level.
        'level' => 2,
        // Section attributes.
        'attributes' => NULL,
        // Section title.
        'title' => t('Chat with documents'),
        // Title attributes.
        'title_attributes' => NULL,
        // Link to the chat form.
        'link' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 *
 * Ensure the attributes and title_attributes are set for the reliefweb
 * templates.
 */
function ocha_ai_chat_preprocess(array &$variables, $hook): void {
  if (strpos($hook, 'ocha_ai_chat_') === 0) {
    foreach ($variables as $key => $value) {
      if ($key === 'attributes' || strpos($key, '_attributes') !== FALSE) {
        if (is_null($value)) {
          $variables[$key] = new Attribute();
        }
      }
    }
  }
}

/**
 * Implements hook_file_download().
 *
 * Allow access to log files to people with the permission to see the logs.
 */
function ocha_ai_chat_file_download(string $uri): mixed {
  if (
    strpos($uri, 'private://ocha_ai_chat_logs/') === 0 &&
    pathinfo($uri, \PATHINFO_EXTENSION) === 'csv' &&
    \Drupal::currentUser()->hasPermission('view ocha ai chat logs')
  ) {
    $filename = \Drupal::service('file_system')->basename($uri);
    return [
      'Content-Disposition' => 'attachment; filename="' . $filename . '"',
      'Content-Length' => filesize($uri),
      'Content-Type' => 'text/csv',
      'Cache-Control' => 'private',
    ];
  }
  return NULL;
}

/**
 * Implements hook_preprocess_html().
 */
function ocha_ai_chat_preprocess_html__ai__chat__popup(array &$variables): void {
  $variables['html_attributes']->addClass('ocha-ai-chat-popup');
}
