ocha_ai_chat.settings:
  type: config_object
  label: 'OCHA AI Chat settings'
  mapping:
    plugins:
      type: mapping
      label: 'List of plugins.'
      mapping:
        completion:
          type: sequence
          label: 'List of completion plugins.'
          sequence:
            type: ocha_ai_chat.plugin.completion.[%key]
            label: 'Settings for a completion plugin.'
        embedding:
          type: sequence
          label: 'List of embedding plugins.'
          sequence:
            type: ocha_ai_chat.plugin.embedding.[%key]
            label: 'Settings for a embedding plugin.'
        source:
          type: sequence
          label: 'List of source plugins.'
          sequence:
            type: ocha_ai_chat.plugin.source.[%key]
            label: 'Settings for a source plugin.'
        text_extractor:
          type: sequence
          label: 'List of completion plugins.'
          sequence:
            type: ocha_ai_chat.plugin.text_extractor.[%key]
            label: 'Settings for a text extractor plugin.'
        text_splitter:
          type: sequence
          label: 'List of text splitter plugins.'
          sequence:
            type: ocha_ai_chat.plugin.text_splitter.[%key]
            label: 'Settings for a text splitter plugin.'
        vector_store:
          type: sequence
          label: 'List of vector store plugins.'
          sequence:
            type: ocha_ai_chat.plugin.vector_store.[%key]
            label: 'Settings for a vector store plugin.'
    defaults:
      type: mapping
      label: 'Default settings.'
      mapping:
        form:
          type: mapping
          label: 'Default form settings.'
          mapping:
            instructions:
              type: string
              label: 'Instructions.'
        plugins:
          type: mapping
          label: 'Default plugins.'
          mapping:
            completion:
              type: mapping
              label: 'Default completion plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            embedding:
              type: mapping
              label: 'Default embedding plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            source:
              type: mapping
              label: 'Default source plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            text_extractor:
              type: sequence
              label: 'Default text extractor plugin settings grouped by file mimetype.'
              sequence:
                type: mapping
                label: 'Default text extractor plugin settings for the mimetype.'
                mapping:
                  plugin_id:
                    type: string
                    label: 'Plugin ID.'
            text_splitter:
              type: mapping
              label: 'Default text splitter plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            vector_store:
              type: mapping
              label: 'Default vector store plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'

### Base plugin settings. ###

# Completion plugin base settings.
ocha_ai_chat.plugin.completion:
  type: mapping
  label: 'Completion plugin settings.'
  mapping:
    model:
      type: string
      label: 'Model name.'
    endpoint:
      type: string
      label: 'Endpoint.'
    version:
      type: string
      label: 'Endpoint.'
    region:
      type: string
      label: 'Endpoint.'
    api_key:
      type: string
      label: 'API key.'
    max_tokens:
      type: integer
      label: 'Max tokens.'
    prompt_template:
      type: string
      label: 'Prompt template'

# Embedding plugin base settings.
ocha_ai_chat.plugin.embedding:
  type: mapping
  label: 'Embedding plugin settings.'
  mapping:
    model:
      type: string
      label: 'Model name.'
    endpoint:
      type: string
      label: 'Endpoint.'
    version:
      type: string
      label: 'Endpoint.'
    region:
      type: string
      label: 'Endpoint.'
    api_key:
      type: string
      label: 'API key.'
    batch_size:
      type: integer
      label: 'Batch size.'
    dimensions:
      type: integer
      label: 'Dimensions.'
    max_tokens:
      type: integer
      label: 'Max tokens.'

# Source plugin base settings.
ocha_ai_chat.plugin.source:
  type: mapping
  label: 'Source plugin base settings.'
  mapping:

# Text extractor plugin base settings.
ocha_ai_chat.plugin.text_splitter:
  type: mapping
  label: 'Text extractor plugin base settings.'
  mapping:

# Text splitter plugin base settings.
ocha_ai_chat.plugin.text_splitter:
  type: mapping
  label: 'Text splitter plugin base settings.'
  mapping:
    length:
      type: integer
      label: 'Maximum length of a text passage.'
    overlap:
      type: integer
      label: 'Number of previous characters, sentences etc. to include to preserve context.'

# Vector store plugin base settings.
ocha_ai_chat.plugin.vector_store:
  type: mapping
  label: 'Vector store plugin base settings.'
  mapping:

### Plugin settings. ###

# AWS Bedrock completion plugin settings.
ocha_ai_chat.plugin.completion.aws_bedrock:
  type: ocha_ai_chat.plugin.completion
  label: 'AWS Bedrock completion plugin settings.'
  mapping:
    api_secret:
      type: string
      label: 'API secret.'
    role_arn:
      type: string
      label: 'AWS role ARN'

# AWS Bedrock embedding plugin settings.
ocha_ai_chat.plugin.embedding.aws_bedrock:
  type: ocha_ai_chat.plugin.embedding
  label: 'AWS Bedrock embedding plugin settings.'
  mapping:
    api_secret:
      type: string
      label: 'API secret.'
    role_arn:
      type: string
      label: 'AWS role ARN'

# Azure OpenAI completion plugin settings.
ocha_ai_chat.plugin.completion.azure_openai:
  type: ocha_ai_chat.plugin.completion
  label: 'AWS Bedrock completion plugin settings.'

# Azure OpenAI embedding plugin settings.
ocha_ai_chat.plugin.embedding.azure_openai:
  type: ocha_ai_chat.plugin.embedding
  label: 'AWS Bedrock embedding plugin settings.'

# ReliefWeb source plugin settings.
ocha_ai_chat.plugin.source.reliefweb:
  type: ocha_ai_chat.plugin.source
  label: 'ReliefWeb source plugin settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    converter_url:
      type: string
      label: 'Search converter URL.'
    appname:
      type: string
      label: 'API appname.'
    cache_enabled:
      type: boolean
      label: 'Cache enabled.'
    cache_lifetime:
      type: integer
      label: 'Cache lifetime.'

# MuPDF text extractor plugin settings.
ocha_ai_chat.plugin.text_extractor.mupdf:
  type: ocha_ai_chat.plugin.text_extractor
  label: 'MuPDF text extractor plugin settings.'
  mapping:
    mutool:
      type: string
      label: 'Mutool executable path.'

# Elasticsearch source plugin settings.
ocha_ai_chat.plugin.vector_store.elasticsearch:
  type: ocha_ai_chat.plugin.vector_store
  label: 'Elasticsearch source plugin settings.'
  mapping:
    url:
      type: string
      label: 'Elasticsearch cluster URL.'
    indexing_batch_size:
      type: integer
      label: 'Number of documents to index at conce'
    topk:
      type: integer
      label: 'Number of nearest neighbours to retrieve when doing similarity search.'
    min_similarity:
      type: float
      label: 'Minimum similarity to be considered relevant.'
    cutoff_coefficient:
      type: float
      label: 'Coefficient for the standard deviation to determine the similarity cut-off for relevancy'
