<?php

namespace Drupal\Tests\ocha_ai\Unit;

use Drupal\ocha_ai\Helpers\TextHelper;
use Drupal\Tests\UnitTestCase;

/**
 * Tests TextHelper.
 *
 * @coversDefaultClass \Drupal\ocha_ai\Helpers\TextHelper
 */
class TextSplitterTest extends UnitTestCase {

  /**
   * Test short string.
   */
  public function testShortString() {
    $length = 384;
    $text = 'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt.

    Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.';

    $expected = [
      'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt. Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.',
    ];

    $result = TextHelper::splitInLinesOptimalLength($text, $length);
    $this->assertEquals($expected, $result);
  }

  /**
   * Test long string.
   */
  public function testLongString() {
    $length = 384;
    $text = 'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt.

    Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.

    Nulla tempor ea reprehenderit dolor veniam est in deserunt eiusmod enim Lorem eu eiusmod et do irure tempor fugiat Lorem qui qui do consectetur ea id laboris dolor nulla sit labore et aliqua quis amet fugiat sunt consectetur qui consectetur pariatur laboris deserunt consectetur occaecat non ex cupidatat nisi aliquip duis laboris amet duis nulla ex fugiat pariatur dolore culpa veniam irure eiusmod dolor excepteur nisi reprehenderit non dolore occaecat labore sunt quis consequat ut reprehenderit magna et velit labore commodo exercitation elit culpa sunt laborum deserunt aute amet quis consectetur enim mollit ullamco tempor adipisicing id proident culpa eiusmod.';

    $expected = [
      'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt. Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.',
      'Nulla tempor ea reprehenderit dolor veniam est in deserunt eiusmod enim Lorem eu eiusmod et do irure tempor fugiat Lorem qui qui do consectetur ea id laboris dolor nulla sit labore et aliqua quis amet fugiat sunt consectetur qui consectetur pariatur laboris deserunt consectetur occaecat non ex cupidatat nisi aliquip duis laboris amet duis nulla ex fugiat pariatur dolore culpa veniam irure eiusmod dolor excepteur nisi reprehenderit non dolore occaecat labore sunt quis consequat ut reprehenderit magna et velit labore commodo exercitation elit culpa sunt laborum deserunt aute amet quis consectetur enim mollit ullamco tempor adipisicing id proident culpa eiusmod.',
    ];

    $result = TextHelper::splitInLinesOptimalLength($text, $length);
    $this->assertEquals($expected, $result);
  }

  /**
   * Test too long string.
   */
  public function testTooLongString() {
    $length = 384;
    $text = 'Et irure consectetur culpa irure duis reprehenderit nisi Lorem dolor consequat exercitation minim commodo tempor deserunt pariatur Lorem incididunt culpa occaecat laborum dolor ullamco nostrud adipisicing magna qui irure adipisicing est pariatur dolor ea labore ea ad ut eu pariatur ex eiusmod mollit labore duis fugiat anim cupidatat ad esse commodo veniam ad magna ipsum anim velit nostrud consequat anim duis in deserunt ea consectetur laborum nostrud sit veniam proident ex reprehenderit mollit excepteur laboris occaecat esse mollit aliquip nostrud eu occaecat labore pariatur velit aliquip ea sit dolor in non sint occaecat aliquip labore adipisicing enim duis anim nulla id eu laboris exercitation ipsum irure amet anim laboris mollit quis consectetur aliqua est labore incididunt id ullamco reprehenderit cupidatat nulla occaecat esse ut consequat ea Lorem adipisicing ut veniam duis elit irure laboris quis fugiat aliquip veniam tempor incididunt quis aliquip ea ut laborum cupidatat reprehenderit culpa mollit dolor laborum duis Lorem ut qui sunt officia eiusmod veniam dolore velit nisi sit aliqua ad dolor magna veniam excepteur culpa id occaecat anim sunt mollit eu ut esse ex do commodo excepteur esse exercitation eu excepteur eiusmod aliqua quis officia amet pariatur sunt consectetur incididunt officia laborum qui duis ut aute nisi aute est ipsum consequat et ut excepteur ea est mollit consectetur non anim excepteur adipisicing esse quis eiusmod non ea tempor labore non mollit magna mollit laboris eiusmod non aliquip tempor culpa reprehenderit aute consequat id aute sit eu est ut cillum mollit irure in minim dolore nostrud consectetur incididunt mollit minim pariatur esse aliqua proident laboris enim sit culpa nulla dolore adipisicing duis enim dolore aliqua nostrud ipsum cupidatat cillum est in duis duis ullamco dolor veniam nisi labore excepteur enim incididunt eiusmod qui tempor Lorem tempor eiusmod cillum culpa amet anim consequat quis amet.';

    $expected = [
      'Et irure consectetur culpa irure duis reprehenderit nisi Lorem dolor consequat exercitation minim commodo tempor deserunt pariatur Lorem incididunt culpa occaecat laborum dolor ullamco nostrud adipisicing magna qui irure adipisicing est pariatur dolor ea labore ea ad ut eu pariatur ex eiusmod mollit labore duis fugiat anim cupidatat ad esse commodo veniam ad magna ipsum anim velit nostrud consequat anim duis in deserunt ea consectetur laborum nostrud sit veniam proident ex reprehenderit mollit excepteur laboris occaecat esse mollit aliquip nostrud eu occaecat labore pariatur velit aliquip ea sit dolor in non sint occaecat aliquip labore adipisicing enim duis anim nulla id eu laboris exercitation ipsum irure amet anim laboris mollit quis consectetur aliqua est labore incididunt id ullamco reprehenderit cupidatat nulla occaecat esse ut consequat ea Lorem adipisicing ut veniam duis elit irure laboris quis fugiat aliquip veniam tempor incididunt quis aliquip ea ut laborum cupidatat reprehenderit culpa mollit dolor laborum duis Lorem ut qui sunt officia eiusmod veniam dolore velit nisi sit aliqua ad dolor magna veniam excepteur culpa id occaecat anim sunt mollit eu ut esse ex do commodo excepteur esse exercitation eu excepteur eiusmod aliqua quis officia amet pariatur sunt consectetur incididunt officia laborum qui duis ut aute nisi aute est ipsum consequat et ut',
      'excepteur ea est mollit consectetur non anim excepteur adipisicing esse quis eiusmod non ea tempor labore non mollit magna mollit laboris eiusmod non aliquip tempor culpa reprehenderit aute consequat id aute sit eu est ut cillum mollit irure in minim dolore nostrud consectetur incididunt mollit minim pariatur esse aliqua proident laboris enim sit culpa nulla dolore adipisicing duis enim dolore aliqua nostrud ipsum cupidatat cillum est in duis duis ullamco dolor veniam nisi labore excepteur enim incididunt eiusmod qui tempor Lorem tempor eiusmod cillum culpa amet anim consequat quis amet.',
    ];

    $result = TextHelper::splitInLinesOptimalLength($text, $length);
    $this->assertEquals($expected, $result);
  }

  /**
   * Test both.
   */
  public function testTooVeryLongString() {
    $length = 384;
    $text = 'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt.

    Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.

    Nulla tempor ea reprehenderit dolor veniam est in deserunt eiusmod enim Lorem eu eiusmod et do irure tempor fugiat Lorem qui qui do consectetur ea id laboris dolor nulla sit labore et aliqua quis amet fugiat sunt consectetur qui consectetur pariatur laboris deserunt consectetur occaecat non ex cupidatat nisi aliquip duis laboris amet duis nulla ex fugiat pariatur dolore culpa veniam irure eiusmod dolor excepteur nisi reprehenderit non dolore occaecat labore sunt quis consequat ut reprehenderit magna et velit labore commodo exercitation elit culpa sunt laborum deserunt aute amet quis consectetur enim mollit ullamco tempor adipisicing id proident culpa eiusmod.

    Et irure consectetur culpa irure duis reprehenderit nisi Lorem dolor consequat exercitation minim commodo tempor deserunt pariatur Lorem incididunt culpa occaecat laborum dolor ullamco nostrud adipisicing magna qui irure adipisicing est pariatur dolor ea labore ea ad ut eu pariatur ex eiusmod mollit labore duis fugiat anim cupidatat ad esse commodo veniam ad magna ipsum anim velit nostrud consequat anim duis in deserunt ea consectetur laborum nostrud sit veniam proident ex reprehenderit mollit excepteur laboris occaecat esse mollit aliquip nostrud eu occaecat labore pariatur velit aliquip ea sit dolor in non sint occaecat aliquip labore adipisicing enim duis anim nulla id eu laboris exercitation ipsum irure amet anim laboris mollit quis consectetur aliqua est labore incididunt id ullamco reprehenderit cupidatat nulla occaecat esse ut consequat ea Lorem adipisicing ut veniam duis elit irure laboris quis fugiat aliquip veniam tempor incididunt quis aliquip ea ut laborum cupidatat reprehenderit culpa mollit dolor laborum duis Lorem ut qui sunt officia eiusmod veniam dolore velit nisi sit aliqua ad dolor magna veniam excepteur culpa id occaecat anim sunt mollit eu ut esse ex do commodo excepteur esse exercitation eu excepteur eiusmod aliqua quis officia amet pariatur sunt consectetur incididunt officia laborum qui duis ut aute nisi aute est ipsum consequat et ut excepteur ea est mollit consectetur non anim excepteur adipisicing esse quis eiusmod non ea tempor labore non mollit magna mollit laboris eiusmod non aliquip tempor culpa reprehenderit aute consequat id aute sit eu est ut cillum mollit irure in minim dolore nostrud consectetur incididunt mollit minim pariatur esse aliqua proident laboris enim sit culpa nulla dolore adipisicing duis enim dolore aliqua nostrud ipsum cupidatat cillum est in duis duis ullamco dolor veniam nisi labore excepteur enim incididunt eiusmod qui tempor Lorem tempor eiusmod cillum culpa amet anim consequat quis amet.

    Quis est ullamco et id labore incididunt esse Lorem sit amet deserunt non labore amet reprehenderit exercitation anim excepteur reprehenderit labore id aute ullamco non adipisicing nisi deserunt tempor aute ipsum ex pariatur enim cupidatat laborum ea consectetur minim excepteur excepteur proident dolore ullamco officia sit tempor laborum ex fugiat deserunt nulla commodo consequat minim consequat elit consectetur qui duis laborum dolor magna anim laboris consectetur adipisicing elit eiusmod cupidatat cupidatat laboris laborum ea culpa cupidatat culpa commodo velit exercitation quis anim laborum consectetur occaecat excepteur aliqua nulla labore ea incididunt anim est irure laborum enim proident pariatur dolore est.

    Duis dolor ipsum sunt irure est aliqua aliquip dolore quis cupidatat pariatur qui excepteur fugiat cupidatat et esse id id commodo eiusmod amet sint qui consectetur excepteur fugiat elit aliqua pariatur dolore ut velit ea id consectetur dolor non officia aliqua ullamco adipisicing nostrud dolore ex excepteur sit anim ad enim deserunt nostrud eiusmod minim Lorem eiusmod magna ipsum culpa irure sunt eiusmod quis ex anim culpa nisi quis Lorem veniam minim ullamco deserunt et ut velit enim eiusmod ex nulla in cillum aliquip non reprehenderit veniam proident non nulla do dolore magna aliquip duis elit ipsum eu ipsum duis. Do veniam culpa officia anim dolore ea labore culpa quis qui nisi Lorem ad exercitation consequat est dolor dolor id do pariatur magna nostrud laborum veniam veniam enim nisi fugiat aliquip veniam do aliqua ea laborum nostrud fugiat in veniam cupidatat non irure aliqua Lorem sint nostrud dolor quis velit occaecat ex mollit adipisicing tempor tempor fugiat proident in quis mollit enim officia id incididunt magna adipisicing anim Lorem fugiat adipisicing labore officia dolor magna reprehenderit exercitation adipisicing nisi consequat et proident laborum dolore id esse culpa eu cupidatat cupidatat irure ea cillum eu dolore ut velit esse ex deserunt. Cillum incididunt quis aute in officia aliquip consectetur consectetur id mollit consequat nisi esse pariatur occaecat ipsum Lorem laborum nulla aliquip anim do qui sunt ipsum magna laboris dolore exercitation cillum cupidatat id ipsum laborum elit ullamco Lorem ea do ex sunt eu sint et tempor consequat consectetur officia consectetur esse ipsum elit ea aliqua commodo ipsum officia commodo aliquip ipsum sit ea irure laborum pariatur cupidatat enim officia aliquip id incididunt tempor cillum ipsum consequat ea dolore excepteur id id duis laborum mollit exercitation deserunt non ut eu esse cupidatat anim aliqua sit tempor officia occaecat ipsum veniam qui.';

    $expected = [
      'Mollit quis sunt do dolore irure aliqua ea magna enim aliquip adipisicing esse culpa id elit labore irure ad tempor enim commodo nulla nisi magna fugiat aute exercitation ex sint quis magna incididunt ut proident ad qui commodo incididunt enim anim et pariatur duis labore amet id ipsum exercitation dolor culpa nulla reprehenderit id magna in do commodo pariatur excepteur amet eu ullamco proident labore et irure proident ad laborum aute laborum id ea ex culpa excepteur eu amet aliquip et sint in deserunt quis aliquip labore labore incididunt non quis aliquip proident laboris consequat pariatur non eu dolore deserunt. Dolore consectetur incididunt magna fugiat ut consequat mollit reprehenderit sit esse dolor non ullamco aliqua nulla irure veniam do exercitation laboris sunt occaecat officia reprehenderit tempor quis irure exercitation labore est consequat dolore commodo sunt est cillum adipisicing elit nulla ex Lorem proident proident nisi culpa esse consectetur irure reprehenderit ipsum do qui esse et velit id do culpa reprehenderit elit nisi officia sit ea non enim occaecat quis excepteur fugiat aliquip sit elit ea veniam sunt labore cillum commodo in ipsum deserunt occaecat nisi pariatur minim eiusmod ipsum quis proident id cillum ullamco consectetur id duis est veniam velit.',
      'Nulla tempor ea reprehenderit dolor veniam est in deserunt eiusmod enim Lorem eu eiusmod et do irure tempor fugiat Lorem qui qui do consectetur ea id laboris dolor nulla sit labore et aliqua quis amet fugiat sunt consectetur qui consectetur pariatur laboris deserunt consectetur occaecat non ex cupidatat nisi aliquip duis laboris amet duis nulla ex fugiat pariatur dolore culpa veniam irure eiusmod dolor excepteur nisi reprehenderit non dolore occaecat labore sunt quis consequat ut reprehenderit magna et velit labore commodo exercitation elit culpa sunt laborum deserunt aute amet quis consectetur enim mollit ullamco tempor adipisicing id proident culpa eiusmod.',
      'Et irure consectetur culpa irure duis reprehenderit nisi Lorem dolor consequat exercitation minim commodo tempor deserunt pariatur Lorem incididunt culpa occaecat laborum dolor ullamco nostrud adipisicing magna qui irure adipisicing est pariatur dolor ea labore ea ad ut eu pariatur ex eiusmod mollit labore duis fugiat anim cupidatat ad esse commodo veniam ad magna ipsum anim velit nostrud consequat anim duis in deserunt ea consectetur laborum nostrud sit veniam proident ex reprehenderit mollit excepteur laboris occaecat esse mollit aliquip nostrud eu occaecat labore pariatur velit aliquip ea sit dolor in non sint occaecat aliquip labore adipisicing enim duis anim nulla id eu laboris exercitation ipsum irure amet anim laboris mollit quis consectetur aliqua est labore incididunt id ullamco reprehenderit cupidatat nulla occaecat esse ut consequat ea Lorem adipisicing ut veniam duis elit irure laboris quis fugiat aliquip veniam tempor incididunt quis aliquip ea ut laborum cupidatat reprehenderit culpa mollit dolor laborum duis Lorem ut qui sunt officia eiusmod veniam dolore velit nisi sit aliqua ad dolor magna veniam excepteur culpa id occaecat anim sunt mollit eu ut esse ex do commodo excepteur esse exercitation eu excepteur eiusmod aliqua quis officia amet pariatur sunt consectetur incididunt officia laborum qui duis ut aute nisi aute est ipsum consequat et ut',
      'excepteur ea est mollit consectetur non anim excepteur adipisicing esse quis eiusmod non ea tempor labore non mollit magna mollit laboris eiusmod non aliquip tempor culpa reprehenderit aute consequat id aute sit eu est ut cillum mollit irure in minim dolore nostrud consectetur incididunt mollit minim pariatur esse aliqua proident laboris enim sit culpa nulla dolore adipisicing duis enim dolore aliqua nostrud ipsum cupidatat cillum est in duis duis ullamco dolor veniam nisi labore excepteur enim incididunt eiusmod qui tempor Lorem tempor eiusmod cillum culpa amet anim consequat quis amet. Quis est ullamco et id labore incididunt esse Lorem sit amet deserunt non labore amet reprehenderit exercitation anim excepteur reprehenderit labore id aute ullamco non adipisicing nisi deserunt tempor aute ipsum ex pariatur enim cupidatat laborum ea consectetur minim excepteur excepteur proident dolore ullamco officia sit tempor laborum ex fugiat deserunt nulla commodo consequat minim consequat elit consectetur qui duis laborum dolor magna anim laboris consectetur adipisicing elit eiusmod cupidatat cupidatat laboris laborum ea culpa cupidatat culpa commodo velit exercitation quis anim laborum consectetur occaecat excepteur aliqua nulla labore ea incididunt anim est irure laborum enim proident pariatur dolore est.',
      'Duis dolor ipsum sunt irure est aliqua aliquip dolore quis cupidatat pariatur qui excepteur fugiat cupidatat et esse id id commodo eiusmod amet sint qui consectetur excepteur fugiat elit aliqua pariatur dolore ut velit ea id consectetur dolor non officia aliqua ullamco adipisicing nostrud dolore ex excepteur sit anim ad enim deserunt nostrud eiusmod minim Lorem eiusmod magna ipsum culpa irure sunt eiusmod quis ex anim culpa nisi quis Lorem veniam minim ullamco deserunt et ut velit enim eiusmod ex nulla in cillum aliquip non reprehenderit veniam proident non nulla do dolore magna aliquip duis elit ipsum eu ipsum duis. Do veniam culpa officia anim dolore ea labore culpa quis qui nisi Lorem ad exercitation consequat est dolor dolor id do pariatur magna nostrud laborum veniam veniam enim nisi fugiat aliquip veniam do aliqua ea laborum nostrud fugiat in veniam cupidatat non irure aliqua Lorem sint nostrud dolor quis velit occaecat ex mollit adipisicing tempor tempor fugiat proident in quis mollit enim officia id incididunt magna adipisicing anim Lorem fugiat adipisicing labore officia dolor magna reprehenderit exercitation adipisicing nisi consequat et proident laborum dolore id esse culpa eu cupidatat cupidatat irure ea cillum eu dolore ut velit esse ex deserunt.',
      'Cillum incididunt quis aute in officia aliquip consectetur consectetur id mollit consequat nisi esse pariatur occaecat ipsum Lorem laborum nulla aliquip anim do qui sunt ipsum magna laboris dolore exercitation cillum cupidatat id ipsum laborum elit ullamco Lorem ea do ex sunt eu sint et tempor consequat consectetur officia consectetur esse ipsum elit ea aliqua commodo ipsum officia commodo aliquip ipsum sit ea irure laborum pariatur cupidatat enim officia aliquip id incididunt tempor cillum ipsum consequat ea dolore excepteur id id duis laborum mollit exercitation deserunt non ut eu esse cupidatat anim aliqua sit tempor officia occaecat ipsum veniam qui.',
    ];

    $result = TextHelper::splitInLinesOptimalLength($text, $length);
    $this->assertEquals($expected, $result);
  }

}
