ocha_ai_chat.settings:
  type: config_object
  label: 'OCHA AI Chat settings'
  mapping:
    plugins:
      type: mapping
      label: 'List of plugins.'
      mapping:
        answer_validator:
          type: sequence
          label: 'List of answer validator plugins.'
          sequence:
            type: ocha_ai.plugin.answer_validator.[%key]
            label: 'Settings for a answer validator plugin.'
        completion:
          type: sequence
          label: 'List of completion plugins.'
          sequence:
            type: ocha_ai.plugin.completion.[%key]
            label: 'Settings for a completion plugin.'
        embedding:
          type: sequence
          label: 'List of embedding plugins.'
          sequence:
            type: ocha_ai.plugin.embedding.[%key]
            label: 'Settings for a embedding plugin.'
        ranker:
          type: sequence
          label: 'List of ranker plugins.'
          sequence:
            type: ocha_ai.plugin.ranker.[%key]
            label: 'Settings for a ranker plugin.'
        source:
          type: sequence
          label: 'List of source plugins.'
          sequence:
            type: ocha_ai.plugin.source.[%key]
            label: 'Settings for a source plugin.'
        text_extractor:
          type: sequence
          label: 'List of completion plugins.'
          sequence:
            type: ocha_ai.plugin.text_extractor.[%key]
            label: 'Settings for a text extractor plugin.'
        text_splitter:
          type: sequence
          label: 'List of text splitter plugins.'
          sequence:
            type: ocha_ai.plugin.text_splitter.[%key]
            label: 'Settings for a text splitter plugin.'
        vector_store:
          type: sequence
          label: 'List of vector store plugins.'
          sequence:
            type: ocha_ai.plugin.vector_store.[%key]
            label: 'Settings for a vector store plugin.'
    defaults:
      type: mapping
      label: 'Default settings.'
      mapping:
        form:
          type: mapping
          label: 'Default form settings.'
          mapping:
            form_title:
              type: string
              label: 'Title of the chat form'
            popup_title:
              type: string
              label: 'Title of the chat popup'
            instructions:
              type: mapping
              label: 'Instructions.'
              mapping:
                value:
                  type: string
                  label: 'Text.'
                format:
                  type: string
                  label: 'Text format.'
            feedback:
              type: string
              label: 'Feedback mode.'
            formatting:
              type: string
              label: 'Formatting mode.'
            answers:
              type: mapping
              mapping:
                no_document:
                  type: string
                  description: 'No document found.'
                no_passage:
                  type: string
                  description: 'No information relevant to the question found.'
                no_answer:
                  type: string
                  description: 'No answer from the AI.'
                invalid_answer:
                  type: string
                  description: 'Answer not matching relevant passages.'
                document_embedding_error:
                  type: string
                  description: 'Error while generating embedding for the documents.'
                question_embedding_error:
                  type: string
                  description: 'Error while generating embedding for the question.'
        plugins:
          type: mapping
          label: 'Default plugins.'
          mapping:
            answer_validator:
              type: mapping
              label: 'Default answer validator plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            completion:
              type: mapping
              label: 'Default completion plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            embedding:
              type: mapping
              label: 'Default embedding plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            ranker:
              type: mapping
              label: 'Default ranker plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
                limit:
                  type: integer
                  label: 'Maximum number of relevant texts to return.'
            source:
              type: mapping
              label: 'Default source plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
            text_extractor:
              type: sequence
              label: 'Default text extractor plugin settings grouped by file mimetype.'
              sequence:
                type: mapping
                label: 'Default text extractor plugin settings for the mimetype.'
                mapping:
                  plugin_id:
                    type: string
                    label: 'Plugin ID.'
            text_splitter:
              type: mapping
              label: 'Default text splitter plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
                length:
                  type: integer
                  label: 'Maximum length of a text passage.'
                overlap:
                  type: integer
                  label: 'Number of previous characters, sentences etc. to include to preserve context.'
            vector_store:
              type: mapping
              label: 'Default vector store plugin settings.'
              mapping:
                plugin_id:
                  type: string
                  label: 'Plugin ID.'
