name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs-drupal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: composer require --dev

      - name: Check coding standards
        run: vendor/bin/phpcs
